"""Create tables

Revision ID: 8a7e4adb9909
Revises: 
Create Date: 2022-05-18 11:45:44.615765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a7e4adb9909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_number', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('response_header_size', sa.Integer(), nullable=False),
        sa.Column('ip_address', sa.String(15), nullable=False),
        sa.Column('response_code', sa.String(32), nullable=False),
        sa.Column('response_size', mysql.INTEGER(display_width=64), nullable=False),
        sa.Column('request_method', sa.String(32), nullable=False),
        sa.Column('report_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('reports')
    # ### end Alembic commands ###
